In [20]:
import numpy as np
import random

In [4]:
# 1. Qiymatlari 10 dan 49 gacha boʻlgan vektor yarating.
array1 = np.arange(10, 50)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# 2. 0 dan 8 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.
array2 = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 3. 3x3 identifikatsiya matritsasi yarating
eyes = np.eye(3, 3, dtype=int)
eyes

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
# 4. Tasodifiy qiymatlar bilan 3x3x3 massiv yarating.
array4 = np.random.randint(1, 100, [3, 3, 3])
array4

array([[[85, 47, 85],
        [56,  5, 70],
        [96, 89, 61]],

       [[52, 85, 92],
        [37,  2, 19],
        [92, 85, 48]],

       [[74, 38, 56],
        [77, 47, 72],
        [42,  6, 83]]], dtype=int32)

In [28]:
# 5. Tasodifiy qiymatlar bilan 10x10 massiv yarating va minimal va maksimal qiymatlarni toping.
array5 = np.random.randint(1, 100, [10, 10])
print(f"Maximum qiymati {array4.max()} ga teng")
print(f"Minumum qiymati {array4.min()} ga teng")

Maximum qiymati 98 ga teng
Minumum qiymati 4 ga teng


In [33]:
# 6. 30 o'lchamdagi tasodifiy vektorni yarating va o'rtacha qiymatni toping.
array6 = np.random.randint(1, 100, 30)
medium = sum(array6) / len(array6)
print(medium)

45.9


In [37]:
# 7. 5x5 tasodifiy matritsani normallashtiring.
array7 = np.random.randint(1, 100, [5, 5])
normalized_matrix = array7 / array7.sum()
normalized_matrix

array([[0.06212252, 0.02329594, 0.02502157, 0.05867127, 0.01725626],
       [0.07161346, 0.03106126, 0.06988783, 0.01725626, 0.05780846],
       [0.01035375, 0.04227783, 0.02070751, 0.05522002, 0.01984469],
       [0.04400345, 0.07765315, 0.00258844, 0.02761001, 0.01639344],
       [0.04141501, 0.04659189, 0.03710095, 0.04314064, 0.0811044 ]])

In [39]:
# 8. 5x3 matritsani 3x2 matritsaga ko'paytiring (haqiqiy matritsa mahsuloti).

arr81 = np.random.randint(1, 20, [5, 3])
dot1 = np.random.randint(1, 20, [3, 2])
a = np.dot(arr81, dot1)
a

array([[206, 135],
       [109,  98],
       [134,  91],
       [242, 168],
       [115,  66]], dtype=int32)

In [42]:
# 9. Ikkita 3x3 matritsa yarating va ularning nuqta mahsulotini hisoblang.
arr91 = np.random.randint(1, 20, [3, 3])
dot2 = np.random.randint(1, 20, [3, 3])
b = np.dot(arr91, dot2)
b

array([[ 89, 209,  59],
       [155, 452, 176],
       [159, 457, 163]], dtype=int32)

In [45]:
# 10. 4x4 matritsa berilgan bo‘lsa, uning ko‘chirilishini toping.
arr101 = np.random.randint(1, 20, [4, 4])
tarnsposed = arr101.transpose()
print(arr101, '\n'+'-'*20)
print(tarnsposed)

[[ 5 17  4 19]
 [ 2 16 11  6]
 [ 1 18  3 13]
 [ 7 16  3 17]] 
--------------------
[[ 5  2  1  7]
 [17 16 18 16]
 [ 4 11  3  3]
 [19  6 13 17]]


In [50]:
# 11. 3x3 matritsa tuzing va uning determinantini hisoblang.
arr11 = np.random.randint(1, 20, [3, 3])
determinant = np.linalg.det(arr11)
print(determinant)


348.00000000000006


In [63]:
# 12. Ikkita A(3x4) va B(4x3) matritsalarni yarating va matritsa mahsulotini A \cdot B hisoblang.
x = np.random.randint(1, 30, [3, 4])
y = np.random.randint(1, 30, [4, 3])
z = np.dot(x, y)
z

array([[ 862,  371,  492],
       [ 970,  351,  603],
       [1392,  558,  878]], dtype=int32)

In [62]:
# 13. 3x3 tasodifiy matritsa va 3 elementli ustun vektorini yarating. Matritsa-vektor mahsulotini hisoblang.
matrix = np.random.randint(1, 20, [3, 3])
a = np.random.randint(1, 20, [3, 1])
result = np.dot(matrix, a)
result


array([[135],
       [280],
       [197]], dtype=int32)

In [67]:
# 14. Chiziqli sistemani Ax = b yeching, bu erda A 3x3 matritsa va b 3x1 ustunli vektor.
A = np.random.randint(1, 30, [3, 3])
B = np.random.randint(1, 30, [3, 1])
x = np.linalg.solve(A, B)
x.T

array([[ 0.26140031,  0.15981479, -0.1464852 ]])

In [59]:
# 15. 5x5 matritsa berilgan boʻlsa, qatorlar va ustunlar boʻyicha yigʻindilarni toping.
arr15 = np.random.randint(1, 20, [5, 5])
b = 0
for i in arr15:
    print(f'{b}-qatorni yigindisi {sum(i)}')
    b += 1
print('-'*20)
for i in range(len(arr15)):
    a = arr15[0, i] + arr15[1, i] + arr15[2, i] + arr15[3, i] + arr15[4, i]
    print(f'{i}-ustunni yigindisi {a}')   
    

0-qatorni yigindisi 32
1-qatorni yigindisi 67
2-qatorni yigindisi 32
3-qatorni yigindisi 27
4-qatorni yigindisi 20
--------------------
0-ustunni yigindisi 32
1-ustunni yigindisi 13
2-ustunni yigindisi 52
3-ustunni yigindisi 33
4-ustunni yigindisi 48
